name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Run detekt
      run: ./gradlew detekt
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
      
    - name: Run common tests
      run: ./gradlew :composeApp:testDebugUnitTest
      
    - name: Run lint checks
      run: ./gradlew lintDebug
      
    - name: Build Android APK
      run: ./gradlew assembleDebug
      
    - name: Build JS
      run: ./gradlew :composeApp:jsBrowserDistribution
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          composeApp/build/reports/tests/
          composeApp/build/test-results/
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: |
          composeApp/build/outputs/apk/debug/
          composeApp/build/dist/js/productionExecutable/

  ios-build:
    name: iOS Build
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build iOS framework
      run: ./gradlew :composeApp:linkDebugFrameworkIosArm64
      
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ios-build-artifacts
        path: composeApp/build/bin/iosArm64/debugFramework/
